include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    avoid_renaming_method_parameters: false
    one_member_abstracts: false
    use_build_context_synchronously: false
    document_ignores: false
