name: quran_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  quran: ^1.3.3
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.2.11

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/json/

  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs1Ver18.otf
    - family: Othmani
      fonts:
        - asset: assets/fonts/Othmani.ttf
    - family: IBMPlex
      fonts:
        - asset: assets/fonts/IBMPlex-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlex-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlex-SemiBold.ttf
          weight: 600
